sudo: required

services:
  - docker

env:
  global:
    - DOCKER_REPO=gwaines
    - DOCKER_IMAGE=nodeinfo
    - DOCKER_USERNAME=gwaines
    - DOCKER_PASSWORD=windriver
    - DEPLOY_SERVER=147.75.92.41
    - DEPLOY_ADMIN_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi11c2VyLXRva2VuLXBxY2JzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlMzMyZDFkNC1iYTE5LTExZTktOTE3Ni1hYzFmNmIwZWVmMjgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.YfgpWrvOCBXSr2CSaYnOTJJAncGe7DjZ915Z0pXmnZzj9d5BLQ0E6PW1OY75UR25LIFX8Ttr4WsLzvAWrkj4BVPjfLtX_nFknGNc6BS1ruhMmiU_M530vX5pIB6bC4QwUKN6g9l2Qcle2hDlJQcP0qQYLkkCkRAaq8Km0rbY5QA_6pEcrg1j74nbiupGFU4AIGMfuT74DFvHlbwfsQUBgX9tbOtlFGlnsBoW8xLpUmoCq-UNw12iWQ0f9i3wjytqCEEJsC1BlFECqvBteLGtQq7oGDn4Qtf6YSKjFMJjOtU-54fS5QMw6J_YROa67xRuV7leOnH_zq1s0OtgPHgjhQ
  
language: python

install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - ./cicd/build-cicd-job.sh
  - ./cicd/test-cicd-job.sh
  
after_success:
  - ./cicd/post-cicd-job.sh ${DOCKER_REPO} ${DOCKER_IMAGE} ${DOCKER_USERNAME} ${DOCKER_PASSWORD}

deploy:
  - provider: script
    script: ./cicd/deploy-cicd-job.sh ${DEPLOY_SERVER} ${DEPLOY_ADMIN_TOKEN}
    on:
      branch: master
