apiVersion: v1
kind: Service
metadata:
  name: nodeinfo
  labels:
    app: nodeinfo
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31115
  selector:
    app: nodeinfo
---
apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nodeinfo-deployment
  labels:
    app: nodeinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeinfo
  template:
    metadata:
      labels:
        app: nodeinfo
    spec:
      containers:
      - name: nodeinfo
        image: guyturgeon/nodeinfo-webserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
